### ISSUE TITLE
what about $useMimeContentType and $useFinfo?

### ISSUE THREAD

**Issue by CybotTM** [cweiske/MIME_Type_PlainDetect#5]
in 
https://github.com/cweiske/MIME_Type_PlainDetect/blame/master/src/MIME/Type/PlainDetect.php#L15

```php
        $mt->useMimeContentType = false;
        //fixme: finfo doesn't give the correct results
        // only fixed in PHP 5.4.4
        $mt->useFileCmd = true;
        $mt->useFinfo = false;
```

is this still an issue?

i am asking because mime type detection fails in /setup at the moment, but enabling $useMimeContentType and $useFinfo fixes this for me.

**Comment by cweiske** [comment]
Probably stale.
